### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by gudianyue** [btma48/AutoLA#3]
When I run test_attention_20.py, I met this error. More details are shown below.

Traceback (most recent call last):
  File "/home/HWL/code/AutoLA/test_attention_20.py", line 187, in <module>
    main()
  File "/home/HWL/code/AutoLA/test_attention_20.py", line 80, in main
    model = Network(CIFAR_CLASSES, genotype)
  File "/home/HWL/code/AutoLA/model_attention.py", line 14, in __init__
    model = attention_resnet20(num_classes=self._num_classes, genotype = self.genotype)
  File "/home/HWL/code/AutoLA/attention_model_test.py", line 221, in attention_resnet20
    model = CifarAttentionResNet(CifarAttentionBasicBlock, 3, num_classes, genotype,**kwargs)
  File "/home/HWL/code/AutoLA/attention_model_test.py", line 179, in __init__
    self.layer1 = self._make_layer(block, self.channel_in,   blocks=n_size, stride=1,step=self._step, genotype=self.genotype)
  File "/home/HWL/code/AutoLA/attention_model_test.py", line 195, in _make_layer
    Block = block(self.inplane, planes,stride,step,genotype)
  File "/home/HWL/code/AutoLA/attention_model_test.py", line 155, in __init__
    self.attention = Attention(self._step, planes, self.genotype)
  File "/home/HWL/code/AutoLA/attention_model_test.py", line 51, in __init__
    self.se = SE(self.C_in,reduction=8)
  File "/home/HWL/code/AutoLA/attention_model_test.py", line 19, in __init__
    nn.Linear(channel // reduction, channel, bias=False),
  File "/home/HWL/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 81, in __init__
    self.reset_parameters()
  File "/home/HWL/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 84, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/HWL/.local/lib/python3.6/site-packages/torch/nn/init.py", line 325, in kaiming_uniform_
    std = gain / math.sqrt(fan)
ZeroDivisionError: float division by zero

**Comment by btma48** [comment]
Sorry, this test_attention_20.py was modified on the ResNet18 on ImageNet, where the base width is 64. On CIFAR10 the base width is 16, and the reduction value may contribute to zero. u may change the  reduction value at self.se = SE(self.C_in,reduction=8).
